apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-default-healthcheck-one
  namespace: healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-default-healthcheck-one
  template:
    metadata:
      labels:
        app: k8s-default-healthcheck-one
    spec:
      containers:
      - name: healthcheck
        image: registry.cn-hangzhou.aliyuncs.com/acs-sample/nginxdemos:latest
        ports:
        - containerPort: 80