apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-default-healthcheck-one
  namespace: healthcheck
  labels:
    app: k8s-default-healthcheck-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-default-healthcheck-one
  template:
    metadata:
      labels:
        app: k8s-default-healthcheck-one
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux