apiVersion: v1
kind: Service
metadata:
  name: k8s-service-default-healthcheck-one
  namespace: healthcheck
  labels:
    app: k8s-service-default-healthcheck-one
spec:
  selector:
    app: k8s-default-healthcheck-one
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80