apiVersion: v1
kind: PersistentVolume
metadata:
  name: proweb-uh-uat-oss-pv
  labels:
    alicloud-pvname: proweb-uh-uat-oss-pv
spec:
  storageClassName: oss
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/oss"
    options:
      bucket: "proweb-uh-uat-pv"
      path: "/"
      url: "oss-cn-hongkong-internal.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
      ramRole: "proweb-uat-uh-k8s-oss-access-role"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proweb-uh-uat-oss-pvc
  namespace: proweb-uh-uat-ns
spec:
  storageClassName: oss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      alicloud-pvname: proweb-uh-uat-oss-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: proweb-uh-uat-nas
  labels:
    alicloud-pvname: proweb-uh-uat-nas
spec:
  storageClassName: nas
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/nas"
    options:
      server: "121c294ae7d-bcu43.cn-hongkong.nas.aliyuncs.com"
      path: "/"
      vers: "4.0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proweb-uh-uat-nas-pvc
  namespace: proweb-uh-uat-ns
spec:
  storageClassName: nas 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      alicloud-pvname: proweb-uh-uat-nas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proweb-uh-uat
  namespace: proweb-uh-uat-ns
  labels:
    app: proweb-uh-uat
    Environment: UAT
    Owner: DigitalChannels
    ProjectName: universityheights
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
  selector:
    matchLabels:
      app: proweb-uh-uat
  template:
    metadata:
      annotations:
        k8s.aliyun.com/eci-sls-enable: "true"
        k8s.aliyun.com/acr-service-arns: "acs:ram::5725926127090411:role/k8s-uat-acr-access"
      labels:
        app: proweb-uh-uat
    spec:
      containers:
      - name: proweb-uh-uat
        # image: registry.cn-hangzhou.aliyuncs.com/acs-sample/nginxdemos:latest
        image: proweb-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/proweb-uat/proweb-uh-uat-acr-repo:latest
        ports:
        - containerPort: 80
        env:
        - name: VARNAME
          value: VARVAL
        - name: aliyun_logs_proweb-uh-uat-log
          value: stdout
        - name: aliyun_logs_proweb-uh-uat-log_project
          value: proweb-uh-uat-log-project
        - name: aliyun_logs_proweb-uh-uat-log_logstore
          value: proweb-uh-uat-log
        - name: aliyun_logs_proweb-uh-uat_machinegroup
          value: proweb-uat-k8s-cluster
        resources:
          requests:
            memory: "1024Mi"  # Initial memory request
            cpu: "256m"       # Initial CPU request
          limits:
            memory: "1024Mi"  # Maximum memory allowed
            cpu: "256m"       # Maximum CPU allowed
        volumeMounts:
        - name: proweb-uh-uat-oss-pvc
          mountPath: "/home/universityheights/public_html/upload/"
        # - name: proweb-uh-uat-nas-pvc
        #   mountPath: "/home/universityheights/public_html/upload/"
      volumes:
      - name: proweb-uh-uat-oss-pvc
        persistentVolumeClaim:
          claimName: proweb-uh-uat-oss-pvc
      # - name: proweb-uh-uat-nas-pvc
      #   persistentVolumeClaim:
      #     claimName: proweb-uh-uat-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: proweb-uh-uat-service
  namespace: proweb-uh-uat-ns
  labels:
    app: proweb-uh-uat-service
spec:
  selector:
    app: proweb-uh-uat
  sessionAffinity: None
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proweb-uh-uat-ingress
  namespace: proweb-uh-uat-ns
  labels:
    ingress: proweb-uh-uat-ingress
  annotations:
    alb.ingress.kubernetes.io/healthcheck-enabled: "true"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-httpversion: "HTTP1.1"
    alb.ingress.kubernetes.io/healthcheck-method: "HEAD"
    alb.ingress.kubernetes.io/healthcheck-code: "http_2xx,http_3xx"
    alb.ingress.kubernetes.io/healthcheck-httpcode: "http_2xx,http_3xx"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthy-threshold-count: "3"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/healthcheck-connect-port: "80"
spec:
  ingressClassName: k8s-alb-https
  rules:
    - host: www-sit.universityheights.hk
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proweb-uh-uat-service
              port:
                number: 80
  tls:
  - hosts: 
    - www-sit.universityheights.hk
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-any-any
  namespace: proweb-uh-uat-ns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
    - {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: proweb-uh-uat-hpa
  namespace: proweb-uh-uat-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proweb-uh-uat
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
