apiVersion: v1
kind: PersistentVolume
metadata:
  name: proweb-ma-prd-oss-pv
  labels:
    alicloud-pvname: proweb-ma-prd-oss-pv
spec:
  storageClassName: oss
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: "alicloud/oss"
    options:
      bucket: "proweb-ma-prd-pv"
      path: "/"
      url: "oss-cn-hongkong-internal.aliyuncs.com"
      otherOpts: "-o max_stat_cache_size=0 -o allow_other"
      ramRole: "proweb-prd-ma-k8s-oss-access-role"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proweb-ma-prd-oss-pvc
  namespace: proweb-ma-prd-ns
spec:
  storageClassName: oss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      alicloud-pvname: proweb-ma-prd-oss-pv
---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: proweb-ma-prd-nas
#   labels:
#     alicloud-pvname: proweb-ma-prd-nas
# spec:
#   storageClassName: nas
#   capacity:
#     storage: 100Gi
#   accessModes:
#     - ReadWriteMany
#   flexVolume:
#     driver: "alicloud/nas"
#     options:
#       server: "125b484a8db-jle43.cn-hongkong.nas.aliyuncs.com"
#       path: "/"
#       vers: "4.0"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: proweb-ma-prd-nas-pvc
#   namespace: proweb-ma-prd-ns
# spec:
#   storageClassName: nas 
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 100Gi
#   selector:
#     matchLabels:
#       alicloud-pvname: proweb-ma-prd-nas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proweb-ma-prd
  namespace: proweb-ma-prd-ns
  labels:
    app: proweb-ma-prd
    Environment: prd
    Owner: DigitalChannels
    ProjectName: mountanderson
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 0
  selector:
    matchLabels:
      app: proweb-ma-prd
  template:
    metadata:
      annotations:
        k8s.aliyun.com/eci-sls-enable: "true"
        k8s.aliyun.com/acr-service-arns: "acs:ram::5725926127090411:role/k8s-prd-acr-access"
      labels:
        app: proweb-ma-prd
    spec:
      containers:
      - name: proweb-ma-prd
        image: proweb-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/proweb-prd/proweb-ma-prd-acr-repo:latest
        ports:
        - containerPort: 80
        env:
        - name: VARNAME
          value: VARVAL
        - name: aliyun_logs_proweb-ma-prd-log
          value: stdout
        - name: aliyun_logs_proweb-ma-prd-log_project
          value: proweb-ma-prd-log-project
        - name: aliyun_logs_proweb-ma-prd-log_logstore
          value: proweb-ma-prd-log
        - name: aliyun_logs_proweb-ma-prd_machinegroup
          value: proweb-prd-k8s-cluster
        resources:
          requests:
            memory: "1024Mi"  # Initial memory request
            cpu: "256m"       # Initial CPU request
          limits:
            memory: "1024Mi"  # Maximum memory allowed
            cpu: "256m"       # Maximum CPU allowed
        volumeMounts:
        - name: proweb-ma-prd-oss-pvc
          mountPath: "/home/mountanderson/public_html/upload/"
        # - name: proweb-ma-prd-nas-pvc
        #   mountPath: "/home/mountanderson/public_html/upload/"
      volumes:
      - name: proweb-ma-prd-oss-pvc
        persistentVolumeClaim:
          claimName: proweb-ma-prd-oss-pvc
      # - name: proweb-ma-prd-nas-pvc
      #   persistentVolumeClaim:
      #     claimName: proweb-ma-prd-nas-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: proweb-ma-prd-service
  namespace: proweb-ma-prd-ns
  labels:
    app: proweb-ma-prd-service
spec:
  selector:
    app: proweb-ma-prd
  sessionAffinity: None
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proweb-ma-prd-ingress
  namespace: proweb-ma-prd-ns
  labels:
    ingress: proweb-ma-prd-ingress
  annotations:
    alb.ingress.kubernetes.io/healthcheck-enabled: "true"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-httpversion: "HTTP1.1"
    alb.ingress.kubernetes.io/healthcheck-method: "HEAD"
    alb.ingress.kubernetes.io/healthcheck-code: "http_2xx,http_3xx"
    alb.ingress.kubernetes.io/healthcheck-httpcode: "http_2xx,http_3xx"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/healthy-threshold-count: "3"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "3"
    alb.ingress.kubernetes.io/healthcheck-connect-port: "80"
spec:
  ingressClassName: k8s-alb-https
  rules:
    - host: www-preprod.mountanderson.com.hk
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: proweb-ma-prd-service
              port:
                number: 80
  tls:
  - hosts: 
    - www-preprod.mountanderson.com.hk
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-any-any
  namespace: proweb-ma-prd-ns
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
    - {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: proweb-ma-prd-hpa
  namespace: proweb-ma-prd-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: proweb-ma-prd
  minReplicas: 1
  maxReplicas: 2
  # behavior:
  #   scaleDown:
  #     stabilizationWindowSeconds: 30 # 30 sec cooldown for scaling down
  #     policies:
  #     - type: Percent
  #       value: 100
  #       periodSeconds: 900 # <20% CPU for 15 minutes
  #   scaleUp:
  #   stabilizationWindowSeconds: 10 # 10 sec cooldown for scaling up
  #     policies:
  #     - type: Percent
  #       value: 100
  #       periodSeconds: 180 # >20% CPU for 3 minutes
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
